global:
  scrape_interval:     15s 
  evaluation_interval: 15s 

rule_files:
# - "first_rules.yml"
# - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: /metrics
    static_configs:
      - targets: 
        - '127.0.0.1:9090'
        - 'api-iris-grp-0.jollybay-57ccde84.westeurope.azurecontainerapps.io'
      
